# Generated by Django 4.2.3 on 2024-12-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitestatistics',
            old_name='visits',
            new_name='game_downloads',
        ),
        migrations.RenameField(
            model_name='sitestatistics',
            old_name='last_visit',
            new_name='last_updated',
        ),
        migrations.AddField(
            model_name='sitestatistics',
            name='site_visits',
            field=models.IntegerField(default=0),
        ),
    ]
